version: "1"
services:
  frontend:
    image: node:latest
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    command: npm start

  backend:
    image: node:latest
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: npm start
