version: "1.0.1"
services:
  app:
    build: ./frontend
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build: ./backend
    networks:
      - internet
      - backend
    ports:
      - 8080:3000
networks:
  backend:
    name: backend
    driver: bridge
  internet:
    name: internet
    driver: bridge
