version: "1"
services:
  app:
    build: ./frontend
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - server
    env_file:
      - ./env.list
  server:
    build: ./backend
    networks:
      - internet
    ports:
      - 27017:3000
    env_file:
      - ./env.list
networks:
  backend:
    name: backend
    driver: bridge
  internet:
    name: internet
    driver: bridge
